insert into public.grants (title, provider, country_region, eligibility, deadline, amount, tags, url)
values
('National STEM Olympiad Track', 'Kazakhstan Youth Science League', 'Kazakhstan', 'Students aged 14-18 with math, informatics, robotics, or science project experience.', '2026-06-15', 'Mentorship + travel support', array['stem','olympiad','research','kazakhstan'], 'https://example.com/stem-olympiad'),
('Youth Founder Microgrant', 'Central Asia Innovation Fund', 'Central Asia', 'Teams or solo students under 19 testing a prototype with real users.', '2026-07-01', '$500-$2,000', array['startup','prototype','entrepreneurship','ai'], 'https://example.com/youth-founder'),
('AI Builders Weekend Hackathon', 'Astana Tech Hub', 'Kazakhstan / Online', 'Beginner to intermediate students who can submit a demo, notebook, or product sketch.', '2026-05-20', 'Prizes + incubator interview', array['hackathon','ai','prototype','portfolio'], 'https://example.com/ai-builders'),
('Almaty Student Innovation Challenge', 'City Innovation Office', 'Almaty, Kazakhstan', 'Students proposing practical solutions for education, climate, mobility, or health.', '2026-08-10', '$1,000 equivalent + pilot support', array['local','innovation','pitch','impact'], 'https://example.com/almaty-innovation'),
('Global Scholarship Readiness Program', 'Future Scholars Network', 'International', 'High school students preparing evidence-based portfolios and personal statements.', '2026-09-05', 'Coaching fellowship', array['scholarship','portfolio','cv','writing'], 'https://example.com/scholarship-readiness'),
('Regional Science Fair: AI for Public Good', 'Eurasia Science Fair', 'Eurasia', 'Students with a research question, dataset, experiment, or technical prototype.', '2026-10-12', 'Awards + mentor network', array['science fair','research','ai','public good'], 'https://example.com/ai-science-fair'),
('Youth Digital Leadership Volunteering Program', 'Open Community Labs', 'Online / Local chapters', 'Students who can teach, document, or lead a small community technology project.', '2026-06-28', 'Certificate + leadership recommendation', array['volunteering','leadership','community','teaching'], 'https://example.com/digital-leadership'),
('International Student Innovators Exchange', 'Frontier Schools Consortium', 'International', 'Students aged 15-18 with proof of initiative, English materials, and a project portfolio.', '2026-11-01', 'Travel stipend + exchange placement', array['international','portfolio','startup','research'], 'https://example.com/innovators-exchange')
on conflict do nothing;
