import type { GoalInput, PathfinderState, ProfileInput, ProgressGraph } from "@/types/pathfinder";
import { seedOpportunities } from "./opportunities";

export const demoProfile: ProfileInput = {
  age: 15,
  city: "Almaty",
  country: "Kazakhstan",
  school: "Nazarbayev Intellectual School",
  grade: "10",
  interests: ["startups", "AI", "research"],
  dailyAvailableTime: 30,
  confidenceLevel: "intermediate",
  achievements: "Some olympiad and project experience.",
};

export const demoGoal: GoalInput = {
  goal: "I want to become an AI founder.",
  targetRole: "AI founder",
  motivation: "Build useful AI products and earn opportunities outside my city.",
  constraints: "30 minutes per day, school schedule, beginner founder network.",
};

export function createDemoGraph(profile: ProfileInput = demoProfile, goal: GoalInput = demoGoal): ProgressGraph {
  const city = profile.city || "your city";
  const country = profile.country || "your country";

  return {
    summary:
      "Path Engine translated the ambition into a proof-driven graph: learn the market, build a tiny AI artifact, package evidence, then use it for grants and competitions.",
    nodes: [
      {
        id: "goal_ai_founder",
        type: "goal",
        title: goal.targetRole || "AI Founder",
        description: goal.goal,
        status: "in_progress",
        x: 0,
        y: 120,
        difficulty: 3,
        xp: 0,
        metadata: { country },
      },
      {
        id: "skill_market",
        type: "skill",
        title: "Market Sense",
        description: "Spot real user pain and explain why AI changes the solution.",
        status: "available",
        x: 280,
        y: 40,
        difficulty: 2,
        xp: 80,
        metadata: { unlocks: ["quest_startup_scan"] },
      },
      {
        id: "quest_startup_scan",
        type: "quest",
        title: "Analyze 3 AI Startups",
        description:
          "Find 3 AI startups launched in the last 2 years. For each, write the problem, target user, why AI matters, and one feature you would improve. Submit a 250-word analysis.",
        status: "available",
        x: 560,
        y: 40,
        difficulty: 2,
        xp: 120,
        metadata: { time: profile.dailyAvailableTime, relatedSkills: ["market research", "product thinking"] },
      },
      {
        id: "skill_prototype",
        type: "skill",
        title: "Prototype Reflex",
        description: "Turn an observed user problem into a small testable AI workflow.",
        status: "locked",
        x: 840,
        y: 34,
        difficulty: 3,
        xp: 160,
        metadata: {},
      },
      {
        id: "quest_tiny_ai_demo",
        type: "quest",
        title: "Build a Tiny AI Concierge",
        description:
          "Create a prompt or no-code workflow that helps a student choose one scholarship or competition. Test it with one classmate and record the feedback.",
        status: "locked",
        x: 1120,
        y: 34,
        difficulty: 3,
        xp: 180,
        metadata: { time: 45, relatedSkills: ["prompting", "user testing"] },
      },
      {
        id: "proof_market_scan",
        type: "proof",
        title: "Market Scan Proof",
        description: "A validated startup analysis artifact demonstrating product research.",
        status: "locked",
        x: 560,
        y: 250,
        difficulty: 1,
        xp: 40,
        metadata: {},
      },
      {
        id: "portfolio_founder_research",
        type: "portfolio",
        title: "Founder Research Artifact",
        description: "A CV-ready item generated from validated proof.",
        status: "locked",
        x: 840,
        y: 250,
        difficulty: 1,
        xp: 80,
        metadata: {},
      },
      {
        id: "grant_ai_builders",
        type: "grant",
        title: "AI Builders Weekend",
        description: `A ${city} / online hackathon match unlocked by proof of AI product research.`,
        status: "locked",
        x: 1120,
        y: 250,
        difficulty: 2,
        xp: 0,
        metadata: { provider: "Astana Tech Hub" },
      },
      {
        id: "milestone_first_signal",
        type: "milestone",
        title: "First Founder Signal",
        description: "You have evidence that you can research, explain, and improve AI products.",
        status: "locked",
        x: 1400,
        y: 140,
        difficulty: 2,
        xp: 250,
        metadata: {},
      },
      {
        id: "skill_user_discovery",
        type: "skill",
        title: "User Discovery",
        description: "Talk to real students and convert messy needs into a sharper founder hypothesis.",
        status: "locked",
        x: 1120,
        y: 470,
        difficulty: 3,
        xp: 160,
        metadata: { relatedSkills: ["interviewing", "problem framing"] },
      },
      {
        id: "quest_student_interview",
        type: "quest",
        title: "Interview 2 Students",
        description:
          "Ask two classmates how they discover competitions or scholarships. Capture exact quotes, missed deadlines, and one workflow you could improve with AI.",
        status: "locked",
        x: 1400,
        y: 470,
        difficulty: 3,
        xp: 180,
        metadata: { time: 35, relatedSkills: ["customer discovery", "synthesis"] },
      },
      {
        id: "portfolio_problem_memo",
        type: "portfolio",
        title: "Problem Discovery Memo",
        description: "A portfolio artifact proving user research, synthesis, and founder judgment.",
        status: "locked",
        x: 1680,
        y: 330,
        difficulty: 2,
        xp: 100,
        metadata: {},
      },
    ],
    edges: [
      { id: "e1", source: "goal_ai_founder", target: "skill_market", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e2", source: "skill_market", target: "quest_startup_scan", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e3", source: "quest_startup_scan", target: "proof_market_scan", relation: "proves", weight: 1, metadata: {} },
      { id: "e4", source: "proof_market_scan", target: "portfolio_founder_research", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e5", source: "portfolio_founder_research", target: "grant_ai_builders", relation: "funds", weight: 0.8, metadata: {} },
      { id: "e6", source: "quest_startup_scan", target: "skill_prototype", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e7", source: "skill_prototype", target: "quest_tiny_ai_demo", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e8", source: "grant_ai_builders", target: "milestone_first_signal", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e9", source: "quest_tiny_ai_demo", target: "skill_user_discovery", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e10", source: "skill_user_discovery", target: "quest_student_interview", relation: "unlocks", weight: 1, metadata: {} },
      { id: "e11", source: "quest_student_interview", target: "portfolio_problem_memo", relation: "proves", weight: 1, metadata: {} },
      { id: "e12", source: "portfolio_problem_memo", target: "milestone_first_signal", relation: "improves", weight: 0.8, metadata: {} },
    ],
    quests: [
      {
        id: "quest_startup_scan",
        nodeId: "quest_startup_scan",
        title: "Analyze 3 AI Startups",
        whyItMatters:
          "Founders win by seeing patterns before others. This quest creates proof that you can study markets and explain product opportunities.",
        instructions:
          "Find 3 AI startups launched in the last 2 years. For each one, write: problem, target user, why AI matters, and one feature you would improve. Finish with a 3-sentence founder insight about Kazakhstan or your school community.",
        expectedOutput: "A 250-350 word analysis with 3 startups and one local founder insight.",
        timeEstimate: Math.max(25, profile.dailyAvailableTime),
        difficulty: 2,
        xpReward: 120,
        relatedSkills: ["market research", "product thinking", "AI literacy"],
        status: "available",
        evaluationRubric: [
          "Names 3 specific AI startups or products.",
          "Explains problem, user, AI advantage, and improvement for each.",
          "Includes one original insight connected to the student context.",
          "Uses concrete examples instead of generic advice.",
        ],
      },
      {
        id: "quest_student_interview",
        nodeId: "quest_student_interview",
        title: "Interview 2 Students",
        whyItMatters:
          "A founder path needs proof that the problem is real. Short interviews create evidence that can strengthen grants, hackathons, and scholarship essays.",
        instructions:
          "Ask two classmates how they currently find competitions, scholarships, or project opportunities. Record exact quotes, where they get stuck, and one AI workflow that could reduce the friction.",
        expectedOutput: "A short interview memo with 2 quotes, 3 pain points, and one AI workflow hypothesis.",
        timeEstimate: 35,
        difficulty: 3,
        xpReward: 180,
        relatedSkills: ["customer discovery", "problem framing", "synthesis"],
        status: "available",
        evaluationRubric: [
          "Includes two distinct student voices or quotes.",
          "Identifies concrete pain points, not broad complaints.",
          "Connects one AI workflow to a real observed problem.",
          "Avoids inventing results or overstating traction.",
        ],
      },
    ],
  };
}

export function createInitialState(profile = demoProfile, goal = demoGoal): PathfinderState {
  return {
    profile,
    goal,
    graph: createDemoGraph(profile, goal),
    proofs: [],
    portfolio: [],
    opportunities: [
      {
        id: "match_ai_builders",
        opportunity: seedOpportunities[2],
        matchScore: 82,
        reason: "Your AI founder goal and first market-research quest map directly to a beginner-friendly AI prototype hackathon.",
        missingRequirements: ["A short prototype demo", "One piece of user feedback"],
        nextAction: "Complete the startup analysis, then unlock the tiny AI demo quest.",
      },
    ],
    xp: 0,
  };
}
