import type { Opportunity } from "@/types/pathfinder";

export const seedOpportunities: Opportunity[] = [
  {
    id: "grant_stem_olympiad_kz",
    title: "National STEM Olympiad Track",
    provider: "Kazakhstan Youth Science League",
    countryRegion: "Kazakhstan",
    eligibility: "Students aged 14-18 with math, informatics, robotics, or science project experience.",
    deadline: "2026-06-15",
    amount: "Mentorship + travel support",
    tags: ["stem", "olympiad", "research", "kazakhstan"],
    url: "https://example.com/stem-olympiad",
  },
  {
    id: "grant_youth_founder",
    title: "Youth Founder Microgrant",
    provider: "Central Asia Innovation Fund",
    countryRegion: "Central Asia",
    eligibility: "Teams or solo students under 19 testing a prototype with real users.",
    deadline: "2026-07-01",
    amount: "$500-$2,000",
    tags: ["startup", "prototype", "entrepreneurship", "ai"],
    url: "https://example.com/youth-founder",
  },
  {
    id: "hackathon_ai_builder",
    title: "AI Builders Weekend Hackathon",
    provider: "Astana Tech Hub",
    countryRegion: "Kazakhstan / Online",
    eligibility: "Beginner to intermediate students who can submit a demo, notebook, or product sketch.",
    deadline: "2026-05-20",
    amount: "Prizes + incubator interview",
    tags: ["hackathon", "ai", "prototype", "portfolio"],
    url: "https://example.com/ai-builders",
  },
  {
    id: "innovation_competition_city",
    title: "Almaty Student Innovation Challenge",
    provider: "City Innovation Office",
    countryRegion: "Almaty, Kazakhstan",
    eligibility: "Students proposing practical solutions for education, climate, mobility, or health.",
    deadline: "2026-08-10",
    amount: "$1,000 equivalent + pilot support",
    tags: ["local", "innovation", "pitch", "impact"],
    url: "https://example.com/almaty-innovation",
  },
  {
    id: "scholarship_prep_global",
    title: "Global Scholarship Readiness Program",
    provider: "Future Scholars Network",
    countryRegion: "International",
    eligibility: "High school students preparing evidence-based portfolios and personal statements.",
    deadline: "2026-09-05",
    amount: "Coaching fellowship",
    tags: ["scholarship", "portfolio", "cv", "writing"],
    url: "https://example.com/scholarship-readiness",
  },
  {
    id: "science_fair_ai",
    title: "Regional Science Fair: AI for Public Good",
    provider: "Eurasia Science Fair",
    countryRegion: "Eurasia",
    eligibility: "Students with a research question, dataset, experiment, or technical prototype.",
    deadline: "2026-10-12",
    amount: "Awards + mentor network",
    tags: ["science fair", "research", "ai", "public good"],
    url: "https://example.com/ai-science-fair",
  },
  {
    id: "volunteer_leadership",
    title: "Youth Digital Leadership Volunteering Program",
    provider: "Open Community Labs",
    countryRegion: "Online / Local chapters",
    eligibility: "Students who can teach, document, or lead a small community technology project.",
    deadline: "2026-06-28",
    amount: "Certificate + leadership recommendation",
    tags: ["volunteering", "leadership", "community", "teaching"],
    url: "https://example.com/digital-leadership",
  },
  {
    id: "international_student_program",
    title: "International Student Innovators Exchange",
    provider: "Frontier Schools Consortium",
    countryRegion: "International",
    eligibility: "Students aged 15-18 with proof of initiative, English materials, and a project portfolio.",
    deadline: "2026-11-01",
    amount: "Travel stipend + exchange placement",
    tags: ["international", "portfolio", "startup", "research"],
    url: "https://example.com/innovators-exchange",
  },
];
